# These are supported funding model platforms

github: [leonpw]
custom: ["https://etherscan.io/enslookup-search?search=slappychuck.eth", "https://polygonscan.com/address/0x0000002e4F99CB1e699042699b91623B1334D2F7"]
