
trigger:
- azure-pipelines

stages:
  - stage: Deploy
    pool:
      name: qemu
    jobs:
      - job: BuildJob
        steps:
          - script: docker build . -t coverletter
          
          
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'